import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Save, Upload, Image as ImageIcon, Sparkles, Plus } from 'lucide-react';
import { Product, productService } from '../services/db';
import { getStorage, ref, uploadBytes, getDownloadURL } from 'firebase/storage';
import { GoogleGenAI, Type } from '@google/genai';
import { useSettings } from '../contexts/SettingsContext';
import toast from 'react-hot-toast';

interface ProductModalProps {
  isOpen: boolean;
  onClose: () => void;
  product?: Product | null;
  onSaved: () => void;
}

export default function ProductModal({ isOpen, onClose, product, onSaved }: ProductModalProps) {
  const { settings } = useSettings();
  const [loading, setLoading] = useState(false);
  const [uploadingImage, setUploadingImage] = useState(false);
  const [generatingAI, setGeneratingAI] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [formData, setFormData] = useState<Partial<Product>>({
    name: '',
    description: '',
    price: 0,
    category: 'Robotics',
    imageUrl: '',
    stock: 0,
    specs: {}
  });

  useEffect(() => {
    if (product) {
      setFormData(product);
    } else {
      setFormData({
        name: '',
        description: '',
        price: 0,
        category: 'Robotics',
        imageUrl: '',
        stock: 0,
        specs: {}
      });
    }
  }, [product, isOpen]);

  const handleAIGenerate = async () => {
    if (!formData.name) {
      toast.error('Please enter a product name first');
      return;
    }

    setGeneratingAI(true);
    try {
      const apiKey = settings.geminiApiKey || process.env.GEMINI_API_KEY;
      if (!apiKey) {
        throw new Error('Gemini API Key is not configured. Please set it in Admin Settings.');
      }
      const ai = new GoogleGenAI({ apiKey });
      const prompt = `Write a professional, technical, and engaging product description for an electronics/robotics component named "${formData.name}". The description should highlight its potential uses for engineers and hobbyists. Keep it under 100 words.`;
      
      const response = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: prompt
      });
      
      if (response.text) {
        setFormData(prev => ({ ...prev, description: response.text.trim() }));
        toast.success('Description generated by AI');
      }
    } catch (error) {
      console.error('AI Generation Error:', error);
      toast.error('Failed to generate description with AI');
    } finally {
      setGeneratingAI(false);
    }
  };

  const handleAIFormatPoints = async () => {
    if (!formData.description) {
      toast.error('Please enter some description or details first');
      return;
    }

    setGeneratingAI(true);
    try {
      const apiKey = settings.geminiApiKey || process.env.GEMINI_API_KEY;
      if (!apiKey) {
        throw new Error('Gemini API Key is not configured. Please set it in Admin Settings.');
      }
      const ai = new GoogleGenAI({ apiKey });
      const prompt = `Convert the following product details into a clean, professional bulleted list of key features. Use "•" for bullets. Ensure each point is concise and technical.
      
      Product Details:
      ${formData.description}`;
      
      const response = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: prompt
      });
      
      if (response.text) {
        setFormData(prev => ({ ...prev, description: response.text.trim() }));
        toast.success('Formatted into points by AI');
      }
    } catch (error) {
      console.error('AI Formatting Error:', error);
      toast.error('Failed to format with AI');
    } finally {
      setGeneratingAI(false);
    }
  };

  const handleAIExtractSpecs = async () => {
    if (!formData.description) {
      toast.error('Please enter a description first to extract specs from');
      return;
    }

    setGeneratingAI(true);
    try {
      const apiKey = settings.geminiApiKey || process.env.GEMINI_API_KEY;
      if (!apiKey) {
        throw new Error('Gemini API Key is not configured. Please set it in Admin Settings.');
      }
      const ai = new GoogleGenAI({ apiKey });
      const prompt = `Extract technical specifications from the following product description.
      
      Description:
      ${formData.description}`;
      
      const response = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: prompt,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              specs: {
                type: Type.OBJECT,
                description: "Key-value pairs of technical specifications",
              }
            },
            required: ["specs"]
          }
        }
      });
      
      if (response.text) {
        const data = JSON.parse(response.text.trim());
        if (data.specs) {
          setFormData(prev => ({ ...prev, specs: { ...(prev.specs || {}), ...data.specs } }));
          toast.success('Specifications extracted by AI');
        }
      }
    } catch (error) {
      console.error('AI Extraction Error:', error);
      toast.error('Failed to extract specs with AI');
    } finally {
      setGeneratingAI(false);
    }
  };

  const handleAISmartFill = async () => {
    if (!formData.description) {
      toast.error('Please enter a description first');
      return;
    }

    setGeneratingAI(true);
    try {
      const apiKey = settings.geminiApiKey || process.env.GEMINI_API_KEY;
      if (!apiKey) {
        throw new Error('Gemini API Key is not configured. Please set it in Admin Settings.');
      }
      const ai = new GoogleGenAI({ apiKey });
      const prompt = `Based on the following product description, suggest a product name, a suitable category (Robotics, Sensors, Power, or Tools), and an estimated price in INR.
      
      Description:
      ${formData.description}`;
      
      const response = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: prompt,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              name: { type: Type.STRING },
              category: { type: Type.STRING, enum: ["Robotics", "Sensors", "Power", "Tools"] },
              price: { type: Type.NUMBER }
            },
            required: ["name", "category", "price"]
          }
        }
      });
      
      if (response.text) {
        const data = JSON.parse(response.text.trim());
        setFormData(prev => ({
          ...prev,
          name: prev.name || data.name,
          category: prev.category === 'Robotics' && !prev.name ? data.category : prev.category,
          price: prev.price === 0 ? data.price : prev.price
        }));
        toast.success('Fields filled by AI');
      }
    } catch (error) {
      console.error('AI Smart Fill Error:', error);
      toast.error('Failed to smart fill with AI');
    } finally {
      setGeneratingAI(false);
    }
  };

  const handleImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files || files.length === 0) return;

    setUploadingImage(true);
    const storage = getStorage();
    
    try {
      const newUrls: string[] = [];
      for (let i = 0; i < files.length; i++) {
        const file = files[i];
        const storageRef = ref(storage, `products/${Date.now()}_${file.name}`);
        const snapshot = await uploadBytes(storageRef, file);
        const downloadURL = await getDownloadURL(snapshot.ref);
        newUrls.push(downloadURL);
      }
      
      setFormData(prev => {
        if (!prev.imageUrl && newUrls.length > 0) {
          return {
            ...prev,
            imageUrl: newUrls[0],
            images: [...(prev.images || []), ...newUrls.slice(1)]
          };
        }
        return {
          ...prev,
          images: [...(prev.images || []), ...newUrls]
        };
      });
      toast.success('Images uploaded successfully');
    } catch (error) {
      console.error('Error uploading images:', error);
      toast.error('Failed to upload images');
    } finally {
      setUploadingImage(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      if (product?.id) {
        await productService.updateProduct(product.id, formData);
        
        // Handle waitlist notification if stock changed from 0 to > 0
        if (formData.stock !== undefined && product.stock === 0 && formData.stock > 0) {
          try {
            const { collection, query, where, getDocs, doc, deleteDoc } = await import('firebase/firestore');
            const { db } = await import('../lib/firebase');
            
            const waitlistSnapshot = await getDocs(query(collection(db, 'waitlists'), where('productId', '==', product.id)));
            const waitlist = waitlistSnapshot.docs.map(d => ({ id: d.id, email: d.data().email }));
            
            if (waitlist.length > 0) {
              // Send emails via API
              await fetch('/api/emails/notify-waitlist', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                  productId: product.id,
                  productName: formData.name || product.name,
                  waitlist: waitlist
                })
              });

              // Remove users from waitlist
              for (const entry of waitlist) {
                await deleteDoc(doc(db, 'waitlists', entry.id));
              }
            }
          } catch (err) {
            console.error('Error processing waitlist:', err);
          }
        }
        
        toast.success('Product updated');
      } else {
        await productService.addProduct(formData as any);
        toast.success('Product added');
      }
      onSaved();
      onClose();
    } catch (error) {
      console.error(error);
      toast.error('Failed to save product');
    } finally {
      setLoading(false);
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-slate-900/40 backdrop-blur-sm z-[100]"
          />
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            className="fixed left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-full max-w-2xl bg-white/95 backdrop-blur-md rounded-3xl shadow-2xl z-[101] overflow-hidden border border-white/40 max-h-[90vh] overflow-y-auto"
          >
            <div className="p-6 md:p-8">
              <div className="flex justify-between items-center mb-8">
                <h2 className="text-2xl font-headline font-bold text-slate-900">
                  {product ? 'Edit Product' : 'Add New Product'}
                </h2>
                <div className="flex items-center gap-3">
                  {!product && (
                    <button
                      type="button"
                      onClick={handleAISmartFill}
                      disabled={generatingAI}
                      className="text-[10px] font-bold uppercase tracking-wider flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-amber-50 text-amber-600 hover:bg-amber-100 transition-colors disabled:opacity-50"
                    >
                      {generatingAI ? (
                        <div className="w-3 h-3 border-2 border-amber-600 border-t-transparent rounded-full animate-spin" />
                      ) : (
                        <Sparkles className="w-3 h-3" />
                      )}
                      Smart Fill (from Desc)
                    </button>
                  )}
                  <button onClick={onClose} className="p-2 hover:bg-slate-100 rounded-full transition-colors text-slate-500">
                    <X className="w-5 h-5" />
                  </button>
                </div>
              </div>

              <form onSubmit={handleSubmit} className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-2">
                    <label className="text-xs font-bold uppercase tracking-widest text-slate-500">Name</label>
                    <input required type="text" value={formData.name} onChange={e => setFormData({...formData, name: e.target.value})} className="w-full px-4 py-3 rounded-xl bg-slate-50 border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-600/50" />
                  </div>
                  <div className="space-y-2">
                    <label className="text-xs font-bold uppercase tracking-widest text-slate-500">Category</label>
                    <select required value={formData.category} onChange={e => setFormData({...formData, category: e.target.value})} className="w-full px-4 py-3 rounded-xl bg-slate-50 border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-600/50">
                      <option value="Robotics">Robotics</option>
                      <option value="Sensors">Sensors</option>
                      <option value="Power">Power</option>
                      <option value="Tools">Tools</option>
                    </select>
                  </div>
                  <div className="space-y-2">
                    <label className="text-xs font-bold uppercase tracking-widest text-slate-500">Price (₹)</label>
                    <input required type="number" step="0.01" value={formData.price} onChange={e => setFormData({...formData, price: e.target.value === '' ? 0 : parseFloat(e.target.value)})} className="w-full px-4 py-3 rounded-xl bg-slate-50 border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-600/50" />
                  </div>
                  <div className="space-y-2">
                    <label className="text-xs font-bold uppercase tracking-widest text-slate-500">MRP (₹) - Optional</label>
                    <input type="number" step="0.01" value={formData.mrp || ''} onChange={e => setFormData({...formData, mrp: e.target.value === '' ? undefined : parseFloat(e.target.value)})} className="w-full px-4 py-3 rounded-xl bg-slate-50 border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-600/50" placeholder="Highest Price" />
                  </div>
                  <div className="space-y-2">
                    <label className="text-xs font-bold uppercase tracking-widest text-slate-500">Stock</label>
                    <input required type="number" value={formData.stock} onChange={e => setFormData({...formData, stock: e.target.value === '' ? 0 : parseInt(e.target.value)})} className="w-full px-4 py-3 rounded-xl bg-slate-50 border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-600/50" />
                  </div>
                  <div className="space-y-2 md:col-span-2 flex items-center gap-3">
                    <input 
                      type="checkbox" 
                      id="isFlashDeal" 
                      checked={formData.isFlashDeal || false} 
                      onChange={e => setFormData({...formData, isFlashDeal: e.target.checked})}
                      className="w-5 h-5 rounded border-slate-300 text-blue-600 focus:ring-blue-600/50"
                    />
                    <label htmlFor="isFlashDeal" className="text-sm font-bold text-slate-700 cursor-pointer">
                      Mark as Flash Deal
                    </label>
                  </div>
                  
                  <div className="space-y-2 md:col-span-2">
                    <label className="text-xs font-bold uppercase tracking-widest text-slate-500">Product Images</label>
                    <input 
                        type="url" 
                        placeholder="Primary Image URL"
                        value={formData.imageUrl || ''}
                        onChange={e => setFormData({...formData, imageUrl: e.target.value})}
                        className="w-full px-4 py-3 rounded-xl bg-slate-50 border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-600/50 text-sm"
                    />
                    <div className="flex flex-col gap-4 items-start">
                      <div className="flex flex-wrap gap-4">
                        {formData.imageUrl && (
                          <div className="relative w-24 h-24 rounded-xl overflow-hidden border border-slate-200 shrink-0">
                            <img src={formData.imageUrl} alt="Preview" className="w-full h-full object-cover" />
                            <div className="absolute bottom-0 left-0 right-0 bg-black/50 text-white text-[8px] text-center py-0.5">Primary</div>
                            <button 
                              type="button"
                              onClick={() => setFormData({...formData, imageUrl: formData.images?.[0] || '', images: formData.images?.slice(1) || []})}
                              className="absolute top-1 right-1 bg-white/80 p-1 rounded-full text-red-500 hover:bg-white"
                            >
                              <X className="w-3 h-3" />
                            </button>
                          </div>
                        )}
                        {formData.images?.map((img, idx) => (
                          <div key={idx} className="relative w-24 h-24 rounded-xl overflow-hidden border border-slate-200 shrink-0">
                            <img src={img} alt={`Preview ${idx}`} className="w-full h-full object-cover" />
                            <button 
                              type="button"
                              onClick={() => setFormData({...formData, images: formData.images?.filter((_, i) => i !== idx)})}
                              className="absolute top-1 right-1 bg-white/80 p-1 rounded-full text-red-500 hover:bg-white"
                            >
                              <X className="w-3 h-3" />
                            </button>
                          </div>
                        ))}
                        <div className="w-24 h-24 rounded-xl border-2 border-dashed border-slate-200 bg-slate-50 flex flex-col items-center justify-center text-slate-400 shrink-0 cursor-pointer hover:bg-slate-100 transition-colors" onClick={() => fileInputRef.current?.click()}>
                          {uploadingImage ? (
                            <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-slate-700"></div>
                          ) : (
                            <>
                              <Upload className="w-6 h-6 mb-1" />
                              <span className="text-[10px] font-bold">Add Image</span>
                            </>
                          )}
                        </div>
                      </div>
                      
                      <div className="flex-1 w-full">
                        <input 
                          type="file" 
                          accept="image/*" 
                          multiple
                          className="hidden" 
                          ref={fileInputRef}
                          onChange={handleImageUpload}
                        />
                        <p className="text-[10px] text-slate-500 mt-2">Or provide an image URL below and click Add</p>
                        <div className="flex gap-2 mt-2">
                          <input 
                            type="url" 
                            id="imageUrlInput"
                            placeholder="https://example.com/image.jpg"
                            className="flex-1 px-4 py-2 rounded-xl bg-slate-50 border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-600/50 text-sm" 
                          />
                          <button
                            type="button"
                            onClick={() => {
                              const input = document.getElementById('imageUrlInput') as HTMLInputElement;
                              if (input.value) {
                                if (!formData.imageUrl) {
                                  setFormData({...formData, imageUrl: input.value});
                                } else {
                                  setFormData({...formData, images: [...(formData.images || []), input.value]});
                                }
                                input.value = '';
                              }
                            }}
                            className="px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl font-bold text-sm transition-colors"
                          >
                            Add
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="space-y-2 md:col-span-2">
                    <div className="flex justify-between items-center">
                      <label className="text-xs font-bold uppercase tracking-widest text-slate-500">Description</label>
                      <div className="flex gap-2">
                        <button
                          type="button"
                          onClick={handleAIGenerate}
                          disabled={generatingAI}
                          className="text-[10px] font-bold uppercase tracking-wider flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-blue-50 text-blue-600 hover:bg-blue-100 transition-colors disabled:opacity-50"
                        >
                          {generatingAI ? (
                            <div className="w-3 h-3 border-2 border-blue-600 border-t-transparent rounded-full animate-spin" />
                          ) : (
                            <Sparkles className="w-3 h-3" />
                          )}
                          Generate Description
                        </button>
                        <button
                          type="button"
                          onClick={handleAIFormatPoints}
                          disabled={generatingAI}
                          className="text-[10px] font-bold uppercase tracking-wider flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-indigo-50 text-indigo-600 hover:bg-indigo-100 transition-colors disabled:opacity-50"
                        >
                          {generatingAI ? (
                            <div className="w-3 h-3 border-2 border-indigo-600 border-t-transparent rounded-full animate-spin" />
                          ) : (
                            <Sparkles className="w-3 h-3" />
                          )}
                          Format as Points
                        </button>
                      </div>
                    </div>
                    <textarea required rows={4} value={formData.description} onChange={e => setFormData({...formData, description: e.target.value})} className="w-full px-4 py-3 rounded-xl bg-slate-50 border border-slate-200 focus:outline-none focus:ring-2 focus:ring-blue-600/50" />
                  </div>

                  <div className="space-y-4 md:col-span-2">
                    <div className="flex justify-between items-center">
                      <label className="text-xs font-bold uppercase tracking-widest text-slate-500">Specifications</label>
                      <button
                        type="button"
                        onClick={handleAIExtractSpecs}
                        disabled={generatingAI}
                        className="text-[10px] font-bold uppercase tracking-wider flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-emerald-50 text-emerald-600 hover:bg-emerald-100 transition-colors disabled:opacity-50"
                      >
                        {generatingAI ? (
                          <div className="w-3 h-3 border-2 border-emerald-600 border-t-transparent rounded-full animate-spin" />
                        ) : (
                          <Sparkles className="w-3 h-3" />
                        )}
                        Extract Specs with AI
                      </button>
                    </div>
                    
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                      {Object.entries(formData.specs || {}).map(([key, value], idx) => (
                        <div key={idx} className="flex gap-2 items-center bg-slate-50 p-2 rounded-xl border border-slate-100">
                          <input 
                            type="text" 
                            value={key} 
                            onChange={(e) => {
                              const newSpecs = { ...formData.specs };
                              const val = newSpecs[key];
                              delete newSpecs[key];
                              newSpecs[e.target.value] = val;
                              setFormData({ ...formData, specs: newSpecs });
                            }}
                            className="flex-1 bg-transparent border-none text-xs font-bold focus:ring-0"
                            placeholder="Label"
                          />
                          <input 
                            type="text" 
                            value={value} 
                            onChange={(e) => {
                              setFormData({ ...formData, specs: { ...formData.specs, [key]: e.target.value } });
                            }}
                            className="flex-1 bg-transparent border-none text-xs focus:ring-0"
                            placeholder="Value"
                          />
                          <button 
                            type="button"
                            onClick={() => {
                              const newSpecs = { ...formData.specs };
                              delete newSpecs[key];
                              setFormData({ ...formData, specs: newSpecs });
                            }}
                            className="p-1 text-red-400 hover:text-red-600"
                          >
                            <X className="w-3 h-3" />
                          </button>
                        </div>
                      ))}
                      <button
                        type="button"
                        onClick={() => setFormData({ ...formData, specs: { ...formData.specs, '': '' } })}
                        className="flex items-center justify-center gap-2 p-2 border-2 border-dashed border-slate-200 rounded-xl text-slate-400 hover:text-slate-600 hover:border-slate-300 transition-all text-xs font-bold"
                      >
                        <Plus className="w-3 h-3" /> Add Spec
                      </button>
                    </div>
                  </div>
                </div>

                <div className="pt-6 border-t border-slate-100 flex justify-end gap-4">
                  <button type="button" onClick={onClose} className="px-6 py-3 text-slate-600 font-bold hover:bg-slate-100 rounded-xl transition-colors">
                    Cancel
                  </button>
                  <button
                    type="submit"
                    disabled={loading || uploadingImage}
                    className="px-8 py-3 bg-blue-600 text-white rounded-xl font-bold hover:bg-blue-700 active:scale-[0.98] transition-all flex items-center gap-2 shadow-lg shadow-blue-600/20 disabled:opacity-50"
                  >
                    <Save className="w-4 h-4" />
                    {loading ? 'Saving...' : 'Save Product'}
                  </button>
                </div>
              </form>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
